/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessPackagesRouteImport } from './routes/wellness-packages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HomeCareRouteImport } from './routes/home-care'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as DoctorsIdRouteImport } from './routes/doctors.$id'

const WellnessPackagesRoute = WellnessPackagesRouteImport.update({
  id: '/wellness-packages',
  path: '/wellness-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCareRoute = HomeCareRouteImport.update({
  id: '/home-care',
  path: '/home-care',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const DoctorsIdRoute = DoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/home-care': typeof HomeCareRoute
  '/locations': typeof LocationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellness-packages': typeof WellnessPackagesRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/home-care': typeof HomeCareRoute
  '/locations': typeof LocationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellness-packages': typeof WellnessPackagesRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/doctors': typeof DoctorsRouteWithChildren
  '/home-care': typeof HomeCareRoute
  '/locations': typeof LocationsRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wellness-packages': typeof WellnessPackagesRoute
  '/doctors/$id': typeof DoctorsIdRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/home-care'
    | '/locations'
    | '/services'
    | '/sitemap.xml'
    | '/wellness-packages'
    | '/doctors/$id'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/home-care'
    | '/locations'
    | '/services'
    | '/sitemap.xml'
    | '/wellness-packages'
    | '/doctors/$id'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/doctors'
    | '/home-care'
    | '/locations'
    | '/services'
    | '/sitemap.xml'
    | '/wellness-packages'
    | '/doctors/$id'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DoctorsRoute: typeof DoctorsRouteWithChildren
  HomeCareRoute: typeof HomeCareRoute
  LocationsRoute: typeof LocationsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WellnessPackagesRoute: typeof WellnessPackagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness-packages': {
      id: '/wellness-packages'
      path: '/wellness-packages'
      fullPath: '/wellness-packages'
      preLoaderRoute: typeof WellnessPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-care': {
      id: '/home-care'
      path: '/home-care'
      fullPath: '/home-care'
      preLoaderRoute: typeof HomeCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/doctors/$id': {
      id: '/doctors/$id'
      path: '/$id'
      fullPath: '/doctors/$id'
      preLoaderRoute: typeof DoctorsIdRouteImport
      parentRoute: typeof DoctorsRoute
    }
  }
}

interface DoctorsRouteChildren {
  DoctorsIdRoute: typeof DoctorsIdRoute
}

const DoctorsRouteChildren: DoctorsRouteChildren = {
  DoctorsIdRoute: DoctorsIdRoute,
}

const DoctorsRouteWithChildren =
  DoctorsRoute._addFileChildren(DoctorsRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DoctorsRoute: DoctorsRouteWithChildren,
  HomeCareRoute: HomeCareRoute,
  LocationsRoute: LocationsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WellnessPackagesRoute: WellnessPackagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
